Neos:
  Flow:
    http:
      middlewares:
        'Wwwision.AssetRealtimeTest:pollingEndpoint':
          position: 'before routing'
          middleware: 'Wwwision\AssetRealtimeTest\PollingEndpointMiddleware'
